### PR TITLE
Resize immediately by default. Add option to defer til window.load

### PR DESCRIPTION
**Pull request by joshuapaling**
As I mentioned in the comment on https://github.com/PaulSpr/jQuery-Flex-Vertical-Center/pull/12, acting on window.load by default is a bad idea. The plugin should act immediately when it is called, and if someone wants, they can just call it on window.load.

Note that even when it's called immediately, it should be called again on window.load, since that's when images, frames etc are fully loaded. Also note that calling it on window.load removes the need to do `$this.find('img').load(resizer);`. I've updated the code to reflect this.

I've also added an additional configuration option, `deferTilWindowLoad` which defaults to false, and which can be set true to allow people to call this plugin from their document.ready, but explicitly avoid the immediate resize, and only get the resize on window.load.

I've also made some adjustments to the readme:
- added doco for existing `debounceTimeout` option
- put code samples into backticks so they'll show properly on the GitHub readme page.

### CODE REVIEW

**Comment by isgit** [comment]
There are some cool things in this commit, but I have 2 issues with it currently:

1) The `deferTilWindowLoad` default value changes old behavior. It might break implementations that call the plugin in the head before any content is loaded.

2) `$this.find('img').load(resizer);` is still needed as far as I'm aware. `$(window).load()` is fired after the HTML is done rendering, but image and iframe request might not have been completed yet. This means that the plugin might center the content without any images being present. Which is  not a problem at the moment, because as soon as they are loaded the `resizer` will fire again and the element will be re-centered

**Comment by PaulSpr** [comment]
Woops, I was signed into the wrong account. I re-posted it as myself:

There are some cool things in this commit, but I have 2 issues with it currently:

1) The `deferTilWindowLoad` default value changes old behavior. It might break implementations that call the plugin in the head before any content is loaded.

2) `$this.find('img').load(resizer);` is still needed as far as I'm aware. `$(window).load()` is fired after the HTML is done rendering, but image and iframe request might not have been completed yet. This means that the plugin might center the content without any images being present. Which is  not a problem at the moment, because as soon as they are loaded the `resizer` will fire again and the element will be re-centered

**Comment by joshuapaling** [comment]
OK, thanks for getting back to me. 

1) The previous PR I referenced, https://github.com/PaulSpr/jQuery-Flex-Vertical-Center/pull/12, changed existing behaviour (albeit a while ago!), and this changes it back. If this project was versioned and using SemVer (http://semver.org/) then the correct way would be to implement `deferTilWindowLoad` but default it to `true` to be consistent with existing behaviour, and then change it to default `false` (which is an overall better default) when the next major version is released.

Since the project isn't versioned, there's basically no obligation on the project's part to maintain backward compatibility, and also no official/right time to introduce breaking changes, either.

So, solutions here would be to either:
a) leave `deferTilWindowLoad` as default `false`. Optionally, you can also introduce SemVer now, and tag this commit as release 1.0.0, to indicate breaking changes, and also indicate that the project will move forward versioned and adhering to SemVer.
or
b) change `deferTilWindowLoad` to default `true`. Even in this case, it'd be a good idea to introduce versioning and SemVer, because otherwise there's never an opportunity to correctly introduce breaking changes.

I'm happy to do either a) or b), let me know which you'd prefer. The versioning part needs to be done by you as project maintainer though.

2) I was looking in to this, and as it turns out, the `load` event is deprecated (see http://stackoverflow.com/questions/12643160/load-method-deprecated), so we should use the new `on` syntax. That's kind of an aside. But either way, the question still is, if you have  `$(window).load()`, do you also need `$this.find('img').load(resizer);`. The answer is no. They are both the same even - load - just done on different selectors. The  `$(window).load()` waits for everything in the entire window to finish, while the `$this.find('img').load(resizer);` only waits for the images in that selection to finish.

`window.load` is the safer bet here (because it waits for all images, frames, etc in the entire page - not just images only, in one section), but both should work OK in most cases. Let me know what you want to do here and I'll amend the PR.

**Comment by joshuapaling** [comment]
Thanks! Want me to send a PR for changing to the 'on' syntax, since `load` is deprecated (as per http://stackoverflow.com/questions/12643160/load-method-deprecated)? Or would you rather resolve that one yourself?

**Comment by PaulSpr** [comment]
You're free to send a PR. As you might have guessed from my super speedy replies I'm a bit busy at the moment ;)

**Pull request merged**
